---
- name: Bootstrap Mac OS
  hosts: local
  tasks:
    - name: Make sure homebrew packages are up-to-date
      community.general.homebrew:
        update_homebrew: true
        upgrade_all: true
      tags:
        - update-brew

    - name: Install tools via ASDF manager
      ansible.builtin.import_tasks: tasks/install/asdf.yml
      vars:
        asdf_tools:
          - plugin: nodejs
            version: "18.15.0"
          - plugin: python
            version: "3.11.3"
          - plugin: ruby
            version: "3.2.2"
          # - plugin: jx  # current plugin does not support Apple Silicon
          #   version: "3.10.83"
      tags:
        - install-asdf

    - name: Install default tools
      ansible.builtin.import_tasks: tasks/install/default.yml
    - name: Install Java (openJDK)
      ansible.builtin.import_tasks: tasks/install/java.yml
    - name: Install system tools
      ansible.builtin.import_tasks: tasks/install/system_tools.yml
    - name: Installer DevOps tools
      ansible.builtin.import_tasks: tasks/install/devops_tools.yml
    - name: Installer developer tools
      ansible.builtin.import_tasks: tasks/install/dev_tools.yml
    - name: Install productivity tools
      ansible.builtin.import_tasks: tasks/install/productivity.yml
    - name: Install extra packages
      ansible.builtin.import_tasks: tasks/install/extra.yml
    - name: Install Kubernetes tools
      ansible.builtin.import_tasks: tasks/install/k8s_tools.yml
    - name: Install Microsoft software
      ansible.builtin.import_tasks: tasks/install/microsoft.yml
    - name: Install Ruby tools
      ansible.builtin.import_tasks: tasks/install/ruby.yml
