---
- name: Bootstrap Mac OS
  hosts: local
  gather_facts: no
  tasks:
    - community.general.homebrew:
        update_homebrew: true
        upgrade_all: true
      tags:
       - update-brew

    - import_tasks: tasks/install_default.yml
    - import_tasks: tasks/install_dev_tools.yml
    - import_tasks: tasks/install_extra.yml
    - import_tasks: tasks/install_k8s_tools.yml
    - import_tasks: tasks/install_microsoft.yml
