Vagrant.configure ("2") do |config|
  # Use a generic Ubuntu 20.04 box for ARM64
  config.vm.box = "generic/ubuntu2004"
  config.vm.box_version = "3.1.16"

  # Use VMware as the provider
  config.vm.provider "vmware_desktop" do |v|
    # Use vmxnet3 as the network adapter type
    v.vmx ["ethernet0.virtualdev"] = "vmxnet3"
    # Enable GUI mode
    v.gui = true
    # Disable linked clone
    v.linked_clone = false
  end
end
