Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  config.vm.box_version = "3.1.16"

  config.vm.provider "vmware_desktop" do |v|
    v.vmx["ethernet0.virtualDev"] = "vmxnet3"
    v.gui = true
    v.linked_clone = false
  end
end
