---
- name: Install asdf dependencies via formula
  vars:
    formula:
      - openssl
      - readline
      - sqlite3
      - xz
      - zlib
  loop: "{{ formula }}"
  community.general.homebrew:
    name: "{{ item }}"

- name: Install asdf tool
  community.general.homebrew:
    name: "asdf"
    state: present

- name: Install asdf plugins
  vars:
    plugins:
      - nodejs
      - python
      - ruby
  ansible.builtin.shell: |
    set -o pipefail
    bash -c '
      for plugin in {{ plugins | join(" ") }}; do
        if ! asdf plugin list | grep -qE "^$plugin"; then
          asdf plugin add $plugin;
        fi;
      done
    '
  register: asdf_plugin_installed
  changed_when: '"updating plugin" in asdf_plugin_installed.stdout'

- name: Install tools managed by asdf plugins
  ansible.builtin.command: "asdf install {{ item.plugin }} {{ item.version }}"
  register: asdf_install_result
  changed_when: asdf_install_result.rc == 1
  loop: "{{ asdf_tools }}"

- name: Set tools as global
  ansible.builtin.command: "asdf global {{ item.plugin }} {{ item.version }}"
  register: asdf_global_result
  changed_when: asdf_global_result.rc == 1
  loop: "{{ asdf_tools }}"

- name: Update asdf plugins
  ansible.builtin.command: "asdf plugin update --all"
  changed_when: false
