---
- name: Install standard tools
  vars:
    formula:
      - fdupes # remove file duplicates
      - midnight-commander
      - rsync
      - tree
  loop: "{{ formula }}"
  community.general.homebrew:
    name: "{{ item }}"
  tags:
    - install-standard

- name: Install ZSH and extensions
  vars:
    formula:
      - zsh
      - zsh-autocomplete
      - zsh-autosuggestions
      - zsh-completions
      - zsh-history-substring-search
      - zsh-syntax-highlighting
  loop: "{{ formula }}"
  community.general.homebrew:
    name: "{{ item }}"
  tags:
    - install-standard
    - install-zsh
