---
- name: Install standard tools
  vars:
    formula:
      - fdupes # remove file duplicates
      - midnight-commander
      - rsync
      - tree
      - zsh-completions
  loop: "{{ formula }}"
  community.general.homebrew:
    name: "{{ item }}"
  tags:
    - install-standard
