---
- name: Install Git tools
  vars:
    formula:
      - gh
      - git
      - git-filter-repo
      - git-lfs
      - gitup
      - libgit2
  loop: "{{ formula }}"
  community.general.homebrew:
    name: "{{ item }}"
  tags:
    - install-dev-tools

- name: Install dev tools via formula
  vars:
    formula:
      - bash
      - direnv
      - shellcheck
      - shfmt
  loop: "{{ formula }}"
  community.general.homebrew:
    name: "{{ item }}"
  tags:
    - install-dev-tools

- name: Install dev tools via casks
  vars:
    cask:
      - anaconda
      - github
      - iterm2
      - keka # file compressor, multiple formats
  loop: "{{ cask }}"
  community.general.homebrew_cask:
    name: "{{ item }}"
  tags:
    - install-dev-tools
