---
- name: Install Git tools
  vars:
    formula:
      - gh # GitHub command-line tool
      - git
      - git-delta # Syntax-highlighting pager for git and diff output
      - git-filter-repo # Quickly rewrite git repository history
      - git-lfs
      - gitup # Update multiple git repositories at once
      - libgit2 # C library of Git core methods that is re-entrant and linkable
  loop: "{{ formula }}"
  community.general.homebrew:
    name: "{{ item }}"
  tags:
    - install-dev-tools

- name: Install dev tools via formula
  vars:
    formula:
      - bash
      - cloc # Statistics utility to count lines of code
      - direnv # Load/unload environment variables based on $PWD
      - jq # Lightweight and flexible command-line JSON processor
      - shellcheck # Static analysis and lint tool, for (ba)sh scripts
      - shfmt # Autoformat shell script source code
  loop: "{{ formula }}"
  community.general.homebrew:
    name: "{{ item }}"
  tags:
    - install-dev-tools

- name: Install dev tools via casks
  vars:
    cask:
      - anaconda
      - github
      - iterm2
      - keka # the macOS file archiver, multiple formats
  loop: "{{ cask }}"
  community.general.homebrew_cask:
    name: "{{ item }}"
  tags:
    - install-dev-tools
