---
- name: Install Terraform tools
  vars:
    formula:
      - tflint
      - tfsec
      - warrensbox/tap/tfswitch
  loop: "{{ formula }}"
  community.general.homebrew:
    name: "{{ item }}"
  tags:
    - install-devops-tools
