---
- name: Install extra tools via formula
  vars:
    formula:
      - gnuplot
  loop: "{{ formula }}"
  community.general.homebrew:
    name: "{{ item }}"
  tags:
    - install-extra-tools

- name: Install extra tools via cask
  vars:
    cask:
      - calibre
      - google-drive
      - xnviewmp
  loop: "{{ cask }}"
  community.general.homebrew_cask:
    name: "{{ item }}"
  tags:
    - install-extra-tools
