---
- name: Install extra tools via formula
  vars:
    formula:
      - ffmpeg
      - gnuplot
      - youtube-dl
  loop: "{{ formula }}"
  community.general.homebrew:
    name: "{{ item }}"
  tags:
    - install-extra-tools

- name: Install extra tools via cask
  vars:
    cask:
      - calibre
      - google-drive
      - google-chrome
      - xnviewmp
  loop: "{{ cask }}"
  community.general.homebrew_cask:
    name: "{{ item }}"
  tags:
    - install-extra-tools
