---
- name: Install K8S tools
  vars:
    formula:
      - fluxcd/tap/flux
      - helm
      - k9s
      - kubectx
      - minikube
  loop: "{{ formula }}"
  community.general.homebrew:
    name: "{{ item }}"
  tags:
    - install-k8s-tools

- name: Install kube-shell via pip
  ansible.builtin.pip:
    name: kube-shell
    state: present
  tags:
    - install-k8s-tools
