name: Ansible lint

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*
      - dependabot/*
    paths-ignore:
      - "**/*.md"

jobs:
  ansible-lint:
    name: Lint Ansible playbooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Check Ansible version
        run: ansible --version

      - name: Run ansible-lint
        uses: ansible/ansible-lint-action@v6.15.0
        with:
          path: "playbook"
