name: Playbook validation with Ansible Lint

on:
  push:
    branches:
      - main
      - feature/*
      - dependabot/*
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint Ansible playbooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check Ansible version
        run: ansible --version

      - name: Run ansible-lint
        uses: ansible/ansible-lint-action@v6.14.4
        with:
          path: "playbook/"
