name: Ansible validation

on:
  push:
    branches:
      - main
      - feature/*
      - dependabot/*
    paths-ignore:
      - "**/*.md"

jobs:
  ansible-lint:
    name: Lint Ansible playbooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Check Ansible version
        run: ansible --version

      - name: Run ansible-lint
        uses: ansible/ansible-lint-action@v6.15.0
        with:
          path: "playbook"

  sonar:
    name: Run SonarCloudu analysis
    uses: kpatryk/workflows/.github/workflows/sonar.yml@v0.1.0
    with:
      os: ubuntu-latest
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
